name: Mac Skor Guncelleme

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3
      
      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Kutuphaneleri kur
        run: pip install requests
      
      - name: Botu calistir
        env:
          FD_API_KEY: ${{ secrets.FD_API_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python bot.py
      
      - name: Guncel veriyi yukle
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add veriler.json
          git commit -m "Gercek veriler guncellendi" || exit 0
          git push
