name: Mac Skor Guncelleme

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri kur
        run: pip install requests

      - name: Botu calistir
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
          # Buraya elindeki her iki anahtarÄ± da ekleyelim ne olur ne olmaz
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python bot.py

      - name: Veriyi Yukle
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add veriler.json
          git commit -m "Guncelleme: $(date)" || exit 0
          git push origin main --force
