name: Mac Skor Guncelleme

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Manuel calistirmak icin

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri kur
        run: pip install requests

      - name: Botu calistir
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python bot.py

      - name: Veriyi Zorla Guncelle
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add veriler.json
          git commit -m "Veriler Guncellendi: $(date)" || echo "Degisiklik yok"
          git push origin main --force
